version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: admin
    group: admin

hooks:
  ApplicationStop:
    - location: bin/application_stop.sh
      timeout: 300
      runas: admin

  BeforeInstall:
    - location: bin/before_install.sh
      timeout: 300
      runas: admin

  AfterInstall:
    - location: bin/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: bin/application_start.sh
      timeout: 60
      runas: admin

  ValidateService:
    - location: bin/validate_service.sh
      timeout: 15
      runas: admin
